context:
  version: "0.30.1"

package:
  name: selene
  version: ${{ version }}

source:
  url: https://github.com/Kampfkarren/selene/archive/${{ version }}.tar.gz
  sha256: 61c66d7e40d8d00fe8364a2696c7f87bcb976d838bd681fd802d427c7675a872

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - selene --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Blazing-fast modern Lua linter
  homepage: https://github.com/Kampfkarren/selene
  repository: https://github.com/Kampfkarren/selene

extra:
  recipe-maintainers:
    - danielnachun
