context:
  version: "0.31.0"

package:
  name: selene
  version: ${{ version }}

source:
  url: https://github.com/Kampfkarren/selene/archive/${{ version }}.tar.gz
  sha256: fa3ef29ce2b698714b7dac6b27ea7b19feaeccf016b0f5e6f328113702be6f04

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - selene --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Blazing-fast modern Lua linter
  homepage: https://github.com/Kampfkarren/selene
  repository: https://github.com/Kampfkarren/selene

extra:
  recipe-maintainers:
    - danielnachun
