context:
  version: "0.28.0"

package:
  name: selene
  version: ${{ version }}

source:
  url: https://github.com/Kampfkarren/selene/archive/${{ version }}.tar.gz
  sha256: c51acf52e7c3136cd0b67b9a39a4a447c8f0257371b2b2acc7e77587260a377b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - selene --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Blazing-fast modern Lua linter
  homepage: https://github.com/Kampfkarren/selene
  repository: https://github.com/Kampfkarren/selene

extra:
  recipe-maintainers:
    - danielnachun
