context:
  version: "0.32.0"

package:
  name: selene
  version: ${{ version }}

source:
  url: https://github.com/Kampfkarren/selene/archive/${{ version }}.tar.gz
  sha256: cd208a4b3bae38decc9c7bb797c19615caaecf67606b3e593ca60b64d3416cd5

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - selene --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Blazing-fast modern Lua linter
  homepage: https://github.com/Kampfkarren/selene
  repository: https://github.com/Kampfkarren/selene

extra:
  recipe-maintainers:
    - danielnachun
