context:
  version: "0.29.0"

package:
  name: selene
  version: ${{ version }}

source:
  url: https://github.com/Kampfkarren/selene/archive/${{ version }}.tar.gz
  sha256: 9882007e7b2d16023cd2c69d64d72afbee65dce7c3ab44a1527f5318667ed2a1

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - selene --help

about:
  license: MPL-2.0
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Blazing-fast modern Lua linter
  homepage: https://github.com/Kampfkarren/selene
  repository: https://github.com/Kampfkarren/selene

extra:
  recipe-maintainers:
    - danielnachun
